Parameters:
  ec2key:
    Type: String
    Default: udacitytestkey
Resources:
  testServer: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-052efd3df9dad4825"
      KeyName: udacitytestkey
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs: 
          VolumeType: "io1"
          Iops: "200"
          DeleteOnTermination: "false"
          VolumeSize: "20"
      - DeviceName: "/dev/sdk"
        NoDevice: {}
      Tags:
        - Key: Project
          Value: udacity
