defaults: &containerenvironment
  docker:
    - image: circleci/node:13.8.0

# define the version of Circle CI to use
version: 2.1
  
# Define a job to be invoked later in a workflow.
jobs:
  create_inventory_file:
    <<: *containerenvironment
    working_directory: /tmp
    steps:
      - checkout
      - run:
          name: Create inventory file
          shell: /bin/sh
          command: |
            chmod 777 create_inventory_file.sh
            ./create_inventory_file.sh
            cp inventory /tmp
      - store_artifacts:
          path: /tmp/inventory
      
# Invoke jobs via workflows
workflows:
  generate_inventory_file:
    jobs:
      - create_inventory_file
  