defaults: &containerenvironment
  docker:
    - image: circleci/node:13.8.0

# define the version of Circle CI to use
version: 2.1
  
# Define a job to be invoked later in a workflow.
jobs:
  create_inventory_file:
    <<: *containerenvironment
    working-directory: ~/home
    steps:
      - checkout
      - run:
          name: Create inventory file
          command: |
            ./godchosen/ansible-practice/CI_CD_Practice/create_inventory_file.sh
      
# Invoke jobs via workflows
workflows:
  generate_inventory_file:
    jobs:
      - create_inventory_file