# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

# Define the orb that would be used
orbs: 
  awscli: circleci/aws-cli@2.0.3

# Define the jobs
jobs:
  # create_infrastructure: 
  #   docker:
  #   - image: amazon/aws-cli
  #   steps:
  #     - checkout
  #     - run:
  #         name: Create Cloudformation Stack
  #         command: |
  #           aws cloudformation deploy \
  #             --template-file template.yml \
  #             --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
  #             --region us-east-1
  configure_infrastructure: 
    docker:
    - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: [28:a5:a3:33:aa:9b:bd:92:3a:86:8c:0d:ac:17:0e:9f]
      - run:
          name: Install Ansible
          command: |
            apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community --update ansible
      - run:
          name: Run Playbook and Configure Server
          command: |
            ansible-playbook -i inventory main-remote.yml
# Invoke jobs via workflows

workflows:
  my-workflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure