---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Remove unwanted dependences"
  become: yes
  apt:
    autoremove: yes

- name: ensure make is installed
  apt: pkg=make state=latest

- name: ensure git is installed
  apt: pkg=git-core state=latest

- name: download n
  git: repo="https://github.com/visionmedia/n" dest=/tmp/n

- name: install n
  command: make -C /tmp/n

- name: install node
  command: n stable

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
  
- name: "Create directory"
  file:
    path: ~/web
    state: directory

- name: "Copy index test page"
  template:
    src: "files/index.js"
    dest: "~/web/index.js" 

- name: "Executing node"
  shell: |
    pm2 start ~/web/index.js -f