---
- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Remove unwanted dependences"
  become: yes
  apt:
    autoremove: yes

# - name: "Install needed dependencies"
#   become: yes
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

- name: add noderesources add_ssh_keys
  become: yes
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add nodesource apt sources
  become: yes
  apt_repository:
    repo: '{{ item }}'
    state: present
  with_items:
    - 'deb https://deb.nodesource.com/node_6.x xenial main'
    - 'deb-src https://deb.nodesource.com/node_6.x xenial main'

- name: install nodejs and npm
  become: yes
  apt: 
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
  
- name: "Create directory"
  file:
    path: ~/web
    state: directory

- name: "Copy index test page"
  template:
    src: "files/index.js"
    dest: "~/web/index.js" 

- name: "Executing node"
  shell: |
    pm2 start ~/web/index.js -f